### ISSUE TITLE
Infinix hot5 firmware

### ISSUE THREAD

**Issue by zeeblaze** [rithvikvibhu/nh-magisk-wifi-firmware#10]
Infinix hot5 firmware for wireless mode

**Comment by rithvikvibhu** [comment]
That looks like a phone. Internal wifi adapters can't be used in Monitor Mode. This module is meant for enabling external adapters via usb.

**Comment by zeeblaze** [comment]
Please make for infinix hot5

**Comment by rithvikvibhu** [comment]
It's simply not possible. Look up kernels for your phone which support network adapters online.

**Comment by zeeblaze** [comment]
I have kernel 3.18.15+ linux kernel

**Comment by rithvikvibhu** [comment]
Most likely a stock kernel which came with your phone. Look into building custom kernels on XDA. I can't really help with kernels.

**Comment by zeeblaze** [comment]
But I dont have a linux os computer

**Comment by rithvikvibhu** [comment]
Can't help you there, sorry.

**Comment by zeeblaze** [comment]
But I think my stock kernel is compatible

**Comment by rithvikvibhu** [comment]
I don't think so. Stock kernels don't really work for this. Did you find anything online saying that the phone supports monitor mode?

**Comment by zeeblaze** [comment]
No...but the kernels which support monitor mode is 3.10+

On Dec 11, 2018 08:50, "Rithvik Vibhu" <notifications@github.com> wrote:

I don't think so. Stock kernels don't really work for this. Did you find
anything online saying that the phone supports monitor mode?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rithvikvibhu/nh-magisk-wifi-firmware/issues/10#issuecomment-446104596>,
or mute the thread
