### ISSUE TITLE
[Request] RT3072 Support

### ISSUE THREAD

**Issue by rhjdvsgsgks** [rithvikvibhu/nh-magisk-wifi-firmware#12]
Please add support for  RT3072

**Comment by rithvikvibhu** [comment]
RT3072 uses the same file as RT3071 and is already included. Did it not work?

**Comment by rhjdvsgsgks** [comment]
Completely not work

lsusb
Bus 001 Device 003: ID 148f:3072  
Bus 001 Device 001: ID 1d6b:0002  
Bus 002 Device 001: ID 1d6b:0003 

dmesg | grep 3072
[28284.951234] usb 1-1: New USB device found, idVendor=148f, idProduct=3072

**Comment by rithvikvibhu** [comment]
Been busy with other work, sorry about the delay.
Can you send the last few line of dmesg right after plugging it in?

**Comment by rhjdvsgsgks** [comment]
Wait few days, please . The Wireless adapter is not in my hands these days .  I'll send you feedback as soon as I get it .
Apologize for my poor English .

**Comment by rithvikvibhu** [comment]
No problem. Whenever you're free.

**Comment by rithvikvibhu** [comment]
Closing all inactive issues. Reopen this whenever you get time.
