### ISSUE TITLE
[REQUEST] Atheros AR9001U-NG (AR9170)

### ISSUE THREAD

**Issue by thedeanius** [rithvikvibhu/nh-magisk-wifi-firmware#13]
I was hoping you might be able to add this chipset to your nifty little magisk module. 
here is the info I could find on it:
https://wikidevi.com/wiki/Netgear_WN111v2

From what I can gather, this one uses the carl9170 driver for linux and therefore isn't covered by the atheros driver you currently have in the module.

Thank You!

**Comment by rithvikvibhu** [comment]
Added. Update to v1.0.5 from Magisk Manager. Let me know how it goes and feel free to reopen if it doesn't work.
