### ISSUE TITLE
Lg g6 h870 nethunter

### ISSUE THREAD

**Issue by ghanimlk** [rithvikvibhu/nh-magisk-wifi-firmware#15]
I nedd a nethunter kernel for my device lg g6 H870, thanks for the help

**Comment by rithvikvibhu** [comment]
This module only adds the drivers for wireless adapters. The kernel must still support it.

A quick search and I couldn't find any kernels for it. You'll likely have to build one yourself. More info here: https://github.com/offensive-security/kali-nethunter/wiki/Porting-Nethunter
