### ISSUE TITLE
Redmi 4x

### ISSUE THREAD

**Issue by Anonymous1p** [rithvikvibhu/nh-magisk-wifi-firmware#16]
There is no kali nethunter or external wifi card support for redmi 4x in pie plz do something. I am using Aex 6.2 pie custom rom. If you will patch the kernel with wifi drivers than plz i have the drivers of an adapter which i bought for redmi 4x in the hope that it will work but not detected by the device , i will send those drivers to you please also be patch them i will never forget your's this great work. Thank you.

**Comment by rithvikvibhu** [comment]
This module only adds the drivers for wireless adapters. The kernel must still support it.

Sorry, I don't compile kernels, only add the required files. Try XDA or the the maintainer for that ROM to include the patches.
