### ISSUE TITLE
[Solicitud] RTL8192CU Soporte

### ISSUE THREAD

**Issue by jamilpardo** [rithvikvibhu/nh-magisk-wifi-firmware#17]
Porfavor ayudame con el soporte para el tp-link tl-wn823n v2 .

**Comment by rithvikvibhu** [comment]
As mentioned in the description, all variants of RTL8192 are already supported. Is it not working? If not please capture a dmesg log right after plugging it into the phone and post it here.

**Comment by jamilpardo** [comment]
https://user-images.githubusercontent.com/47122122/52950715-f8bac980-334d-11e9-9783-f4763fdbadf0.jpg
https://user-images.githubusercontent.com/47122122/52950646-cb6e1b80-334d-11e9-9688-f6d4fbab09ec.jpg
https://user-images.githubusercontent.com/47122122/52950655-d163fc80-334d-11e9-840d-d5e1c16a3a04.jpg)

**Comment by rithvikvibhu** [comment]
There's nothing about the adapter itself, just a usb hub. Is the adapter powered and lighting up (if it has an led indicator)? Try plugging it in directly without the hub.

**Comment by jamilpardo** [comment]
And this comes to me by running direct dmes from the terminal
ttps://user-images.githubusercontent.com/47122122/52951606-45070900-3350-11e9-8d68-aaebb3ce4ffb.jpg
https://user-images.githubusercontent.com/47122122/52951607-459f9f80-3350-11e9-99b6-0e7d66be4abf.jpg
https://user-images.githubusercontent.com/47122122/52951608-459f9f80-3350-11e9-824b-c421bcbc5a91.jpg
https://user-images.githubusercontent.com/47122122/52951609-459f9f80-3350-11e9-9683-8a10b8ae3b81.jpg

**Comment by jamilpardo** [comment]
If clear is connected by otg to my cell phone samsung galaxy j7 prime The led indicator of the wifi adapter does not turn on and when I run the iwconfig command only my internal network card appears on my cell phone; tp link tl-wn823n does not appear.

**Comment by rithvikvibhu** [comment]
Hm. What about `lsusb` and `lspci`?

**Comment by jamilpardo** [comment]
Hello this appears to me when executing those commands

El mié., 20 de feb. de 2019 07:37, Rithvik Vibhu <notifications@github.com<mailto:notifications@github.com>> escribió:

Hm. What about lsusb and lspci?

**Comment by jamilpardo** [comment]
Hello this appears to me when executing those commands
https://user-images.githubusercontent.com/47122122/53092889-eecacf00-34e3-11e9-98c6-567f98e9f336.jpg

**Comment by rithvikvibhu** [comment]
People facing the same issue could fix it here: https://github.com/Mange/rtl8192eu-linux-driver
That requires compiling drivers, which I can't help much. You can give it a try and see if it works.
