### ISSUE TITLE
[Solicitud] RT3070 Soporte

### ISSUE THREAD

**Issue by jamilpardo** [rithvikvibhu/nh-magisk-wifi-firmware#18]
Please helpme with the suport for the adapter wifi Lin-fox LF -850000000G

**Comment by rithvikvibhu** [comment]
As mentioned in the description, all RT3070 is already supported. Is it not working? If not please capture a dmesg log right after plugging it into the phone and post it here.

**Comment by jamilpardo** [comment]
I still do not acquire the antenna; but I want to be sure that it works to acquire it. I looked for it in wikipedia or something similar and it was there that the Lin-fox antenna has the RT3070 chipset.

**Comment by rithvikvibhu** [comment]
Well, it's supported. If it doesn't work, feel free to reopen this.
