### ISSUE TITLE
Atheros AR9271 Firmware

### ISSUE THREAD

**Issue by lucaterpirla** [rithvikvibhu/nh-magisk-wifi-firmware#2]
It would be great if you could update your module with this chip's firmware as well

**Comment by rithvikvibhu** [comment]
This is already included as htc_9271. If it doesn't work, can you post the latest dmesg?

**Comment by lucaterpirla** [comment]
Now that I tried, it does work well. I can see the wlan1 as Atheros communication chip 9271 when I do "iwconfig". That's great, thanks for this module. Respect.
