### ISSUE TITLE
[Request] ath9k_htc

### ISSUE THREAD

**Issue by lnViztor** [rithvikvibhu/nh-magisk-wifi-firmware#20]

**Comment by rithvikvibhu** [comment]
ath9k_htc provides support for AR7010 and AR9271 chipsets. These are already included.

Which device are you trying to use?

**Comment by lnViztor** [comment]
Im trying use 722n v1.0 but  after flashing in termux, ,**ifconfig wlan1 up**, dosn't raise my adapter. I'm using HolyDragon kernel 0.6.0 and Omnidragon ROM and i want have driver compatibilty with Andrax.

**Comment by lnViztor** [comment]
I dont know if this is posible. thaks for your work.

**Comment by rithvikvibhu** [comment]
A quick search and found https://forum.xda-developers.com/oneplus-3/oneplus-3--3t-cross-device-development/kernel-holydragon-kernel-t3732974

Is this the kernel? The features list doesn't say anything about nethunter, external usb adapters, etc. This module only adds the required firmware to use the devices. But the kernel still has to support it.

Request the kernel maintainer or try another kernel.

**Comment by lnViztor** [comment]
Sorry I was wrong I thought that the module included the drivers in the kernel but it is silly, the kernel must be compiled with the drivers. Yes, it is that kernel and this is what I really need for my adapter to work, a kernel already compiled with the driver.

https://forum.xda-developers.com/oneplus-3/oneplus-3--3t-cross-device-development/kernel-coconut-kernel-nethunter-support-t3908438

Thanks. best regards.

**Comment by rithvikvibhu** [comment]
Hope you get it working!

**Comment by huitc** [comment]
how? tell me!!! t.t @lnViztor @rithvikvibhu

**Comment by lnViztor** [comment]
@huitc what's are you singing?

**Comment by huitc** [comment]
ath9k_htc @lnViztor

**Comment by lnViztor** [comment]
You are very little explicit, you need only read and answer you.

**Comment by huitc** [comment]
?

**Comment by huitc** [comment]
when I plug in my USB wifi dongle and type `ifconfig`--> nothinggggg.......

(`lsusb` ok
