### ISSUE TITLE
can you support tenda u12 and TP-LINK TL-WN821N?

### ISSUE THREAD

**Issue by huitc** [rithvikvibhu/nh-magisk-wifi-firmware#23]
I have a tenda u12 and TP-LINK TL-WN821N v3
but... They are not in the supported list

https://wikidevi.com/wiki/TP-LINK_TL-WN821N_v3
https://wikidevi.com/wiki/Tenda_U12

https://github.com/rithvikvibhu/nh-magisk-wifi-firmware/issues/11
https://github.com/rithvikvibhu/nh-magisk-wifi-firmware/issues/20
https://github.com/rithvikvibhu/nh-magisk-wifi-firmware/issues/16

thx!!

**Comment by huitc** [comment]
I'm using xiaomi mi6

**Comment by rithvikvibhu** [comment]
Pushed v2.0.1 with both of them. I couldn't find an AU version for rtl8812, so hopefully, the AE one will work. Let me know how it goes! Reopen the issue if it doesn't work.

**Comment by huitc** [comment]
https://github.com/aircrack-ng/rtl8812au

**Comment by huitc** [comment]
> Added AR7010 and RTL8821 (v2.0.1)
not 8812?

**Comment by huitc** [comment]
it's just me? or?
xiaomi mi6 Android 8.0.0
![Screenshot_2019-04-19-06-50-44-721_com offsec nhterm](https://user-images.githubusercontent.com/20995449/56396110-f43c5f80-626f-11e9-9788-dbf1f1f64243.png)

**Comment by rithvikvibhu** [comment]
> 
> 
> > Added AR7010 and RTL8821 (v2.0.1)
> 
> not 8812?

The driver is actually for 8821, but is supposed to work for 8812 also.
