### ISSUE TITLE
Rtl8188eu not work but can identify

### ISSUE THREAD

**Issue by wangmu0579** [rithvikvibhu/nh-magisk-wifi-firmware#27]
We can see usb wifi identify but wifite only have wlan0.
could some one help?

root@kali:/lib# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 0bda:8179 Realtek Semiconductor Corp. RTL8188EUS 802.11n Wireless Network Adapter
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
root@kali:/lib#
root@kali:/lib
wifite output
Interface PHY Driver Chipset
p2p0 phy0 icnss Not pci, usb, or sdio
wlan0 phy0 icnss Not pci, usb, or sdio

My problem should be:My external wifi network usb dongle RTL8188eu can't work on onePlus6T.
Could some one help?

**Comment by rithvikvibhu** [comment]
Not sure how I missed this, but this has already been covered at #25. As a hail mary, I even added all files for RTL on May 9th. If you're using the latest version of the module (like 2.0.2 or 2.0.3), then mostly the drivers aren't correct, the kernel doesn't support it or some other problem.
Anyway, check out #25.
