### ISSUE TITLE
Modules Not Loading In Nethunter

### ISSUE THREAD

**Issue by shakim24** [rithvikvibhu/nh-magisk-wifi-firmware#29]
So I'm trying to load the driver modules manually in Nethunter (v2019.2) and it is not loading at all. I flashed the Nethunter klte kernel nougat. My device I'm using is GS5, I installed Nethunter through Magisk Module. When I type "find /lib/modules/3.4.114-nethunter-klte-spr-3.0 -type f -name athk9k*" in Kali I get a error saying "no such file or directory". When in type "modprobe -rtv ath9k" I get a error saying "modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/3.4.113-nethunter-klte-spr-3.0/modules.dep.bin" so trying to load this in kali just isn't working. So I tried running "find /lib/modules/3.4.114-nethunter-klte-spr-3.0 -type f -name athk9k*" in Android su it finds the files with no problem, it lists them. So I decided to run these commands in Android su: modprobe -rtv ath9k_htc.ko
 rfkill unblock all modprobe -v ath9k_htc.ko 
It errors out saying modprobe: module 'ath9k_htc.ko*' not found. Insmod brings up a "no such file or directory". I get the same error when i replace ath9k_htc.ko with ath or ath9k  What's going on!!!! I've never had issues loading ath9k drivers through Nethunter. I need help. My wifi adapter is TP-LINK WN722N v1.

**Comment by kimocoder** [comment]
Update the NetHunter app to v2019.3-rc1 -- fixes the modules autoloading feature so you don't need to load modules in Android SU before entering NetHunter chroot

![IMG_20190602_190829](https://user-images.githubusercontent.com/4252297/58766647-6eefde80-8581-11e9-9643-1a04c9a4bd70.jpg)

**Comment by kimocoder** [comment]
And for even easier control of the modules, download the "KoControl" app

![IMG_20190602_195620](https://user-images.githubusercontent.com/4252297/58766679-b5453d80-8581-11e9-9538-1da97b1172c2.jpg)

**Comment by shakim24** [comment]
@kimocoder thank you for the quick response. I will give it a try.

**Comment by shakim24** [comment]
@kimocoder is the KoControl app in Magisk?

**Comment by kimocoder** [comment]
No problem :+1: 
https://gitlab.com/kalilinux/nethunter/apps/kali-nethunter-app/releases

**Comment by kimocoder** [comment]
No it's not, we're working to integrate it into NetHunter, the developer sent the sources today.
Until then, use https://m.apkpure.com/kocontrol/com.faust93.kocontrol

**Comment by shakim24** [comment]
@kimocoder What's with this error "modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/3.4.113-nethunter-klte-spr-3.0/modules.dep.bin" what is it from?

**Comment by shakim24** [comment]
@kimocoder still not loading up modules and it's running the latest nethunter apk.
![2019-06-03 00 37 18](https://user-images.githubusercontent.com/8216564/58776293-f3e5f280-8597-11e9-914f-bb4e887fa200.jpg)

**Comment by haroonalhadisk** [comment]
@kimocoder can't see the modules in kocontrol and lsmod returns only f2fs. Please help I need mt7601u to load.

**Comment by Taco-Network** [comment]
I have this issue too. No modules and updated to latest. KO control is blank.

**Comment by VincenzoScrima** [comment]
> @kimocoder still not loading up modules and it's running the latest nethunter apk.
> ![2019-06-03 00 37 18](https://user-images.githubusercontent.com/8216564/58776293-f3e5f280-8597-11e9-914f-bb4e887fa200.jpg)
> 
> Edit: all is well. Drivers are loading now.

I have the same problem, how did you fixed it?

**Comment by yuza1998** [comment]
me too 

> > @kimocoder still not loading up modules and it's running the latest nethunter apk.
> > ![2019-06-03 00 37 18](https://user-images.githubusercontent.com/8216564/58776293-f3e5f280-8597-11e9-914f-bb4e887fa200.jpg)
> > Edit: all is well. Drivers are loading now.
> 
> I have the same problem, how did you fixed it?

me too i already install kernel nethunter for my poco x3..but no modules..cant use externel wifi..and hid..howto load modules ?

**Comment by marci-n-owak** [comment]
I am facing right now the same issue with no modules on `lsmod` on my Nexus 5x with everything updated... Anyone can help with that?

**Comment by Zarale00** [comment]
> I am facing right now the same issue with no modules on `lsmod` on my Nexus 5x with everything updated... Anyone can help with that?

did you fixed that?
