### ISSUE TITLE
TL-WN722N v3 is in support?

### ISSUE THREAD

**Issue by Si-i3ima** [rithvikvibhu/nh-magisk-wifi-firmware#33]
I have : Xiaomi Redmi 5 plus ( vince ) with NitrogenOS installed,i have custom kernel(I can give you a link,can't test because don't know working or not),I already tried KaliNethunter magisk module,NaliNethunter, Andrax. And every time i have a problem, here is my lsusb log and iwconfig log 
```
root@kali:~# lsusb Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 2357:010c TP-Link TL-WN722N v2
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

```
![96VAICcVehA (1)](https://user-images.githubusercontent.com/17309019/63607076-745c3400-c586-11e9-8448-4432e4a29759.jpg)

I tested this adapter on my computer with this driver  [https://github.com/kimocoder/rtl8188eus](url) ,seems work.
But my smartphone don't see adapter

UPD : found official driver with monitor mode support : [https://static.tp-link.com/2018/201805/20180521/TP-Link_Driver_Linux_series7_beta.zip](url)

**Comment by rithvikvibhu** [comment]
RTL8188EUS is the chipset for WN722N v3. This is already included. The problem is likely that the kernel should add the driver. This module only provides the required firmware files which are used later on.

**Comment by Kry9toN** [comment]
Does it support monitor mode?

**Comment by kimocoder** [comment]
Both monitor mode and frame injection is supported. But only on v5.3.9 branch atm, haven't had time to finish the newest release (branch) yet

**Comment by Kry9toN** [comment]
Oh nice, hopefully there's time to finish

**Comment by Si-i3ima** [comment]
So @kimocoder make v5.3.9 branch as default branch, and now i think it's working

**Comment by Si-i3ima** [comment]
@rithvikvibhu  Will you update your module?

**Comment by rithvikvibhu** [comment]
I really don't have time right now. If you or someone can build and send the binary, I'll include it in the package.

**Comment by Si-i3ima** [comment]
@rithvikvibhu Okay, I build .ko how I can sent it to you?

**Comment by rithvikvibhu** [comment]
I'm sorry, I wasn't thinking straight. This Magisk module is to provide firmware files. Not drivers.
This firmware is what runs on the adapter (not the host).

It's not a replacement for the driver itself. And copying the .ko shouldn't really work.

**Comment by Si-i3ima** [comment]
So what can I do?

**Comment by rithvikvibhu** [comment]
It's something to do with drivers. I can't say :/

**Comment by Si-i3ima** [comment]
Well at least thanks for the answer
