### ISSUE TITLE
please add TL-WN822N driver V5

### ISSUE THREAD

**Issue by hear1314** [rithvikvibhu/nh-magisk-wifi-firmware#35]

**Comment by rithvikvibhu** [comment]
TL-WN822N v5 uses RTL8192EU. This is already included.
Make sure to get the latest version of this module (v2.0.3 as of now). Also, make sure your kernel supports it.
Feel free to reopen this if it still doesn't work.

**Comment by hear1314** [comment]
can I flash it with twrp because I already install nethunter
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Họ và tên: Lê Tuấn Huy
SN: 13/01/2003
Đ/c: Số nhà 35 - Phố Tây Sơn - Thị trấn Phùng - H.Đan Phượng - Hà Nội
Mobile: 0902130103 - 0969356812
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Vào Th 3, 1 thg 10, 2019 vào lúc 00:14 Rithvik Vibhu <
notifications@github.com> đã viết:

**Comment by rithvikvibhu** [comment]
It works just fine with NetHunter. It can be installed through TWRP or Magisk Manager.
