### ISSUE TITLE
lsusb works but iwconfig doesn't

### ISSUE THREAD

**Issue by tahmidamit** [rithvikvibhu/nh-magisk-wifi-firmware#37]
So this is the problem when I used The TP link 722n v1 usb it worked fine both lsusb and iwconfig showed the adapter but when I tried the new adapter which has a mt701u chipset it does show that the adapter is connected and lsusb shows that the adapter is connected.
But when I use iwconfig it doesn't show any external interface. I am using your module with a custom nethunter kernel. Any solution?

**Comment by rithvikvibhu** [comment]
I think you mean mt7601u?

This is supported, and firmware files are included.
If lsusb shows, and iwconfig doesn't, It's usually that the kernel doesn't support this driver.
