### ISSUE TITLE
Support Kali Nethunter in Magisk

### ISSUE THREAD

**Issue by adi90x** [rithvikvibhu/nh-magisk-wifi-firmware#38]
Hello, 

Any way to support the nethunter version that is available from Magisk repo ? 

Regards

**Comment by rithvikvibhu** [comment]
As the description and README states, it works with all varients of nethunter, including Nali Kethunter.

**Comment by adi90x** [comment]
Nevermind, in fact firmware are already include on the version available on
Magisk at the moment

Le lun. 11 nov. 2019 à 19:24, Rithvik Vibhu <notifications@github.com> a
écrit :
