### ISSUE TITLE
Please add driver rtl8188fu

### ISSUE THREAD

**Issue by logantmg** [rithvikvibhu/nh-magisk-wifi-firmware#39]
Would you please add driver rtl8188fu here's the source of driver https://github.com/ulli-kroll/rtl8188fu        thank you

**Comment by logantmg** [comment]
![Screenshot_2019-11-15-07-36-37-654_com offsec nhterm](https://user-images.githubusercontent.com/57450542/68913389-3afd2400-0783-11ea-94dd-7eb23c2ec8b2.jpg)

**Comment by logantmg** [comment]
It shows in lsusb but not in ifconfig iwconfig airmon maybe the driver is not installed so please help me

**Comment by rithvikvibhu** [comment]
Searched and there isn't any separate firmware required for RTL8188FU, or it uses the same one as the EU version (which this module supports).

If it shows up in lsusb and not in ifconfig, then you'll mostly need to find a kernel that supports this card (try XDA maybe?). This module only provides the firmware files.

**Comment by rithvikvibhu** [comment]
I can't say. Try asking on XDA or the kernel's maintainer.

**Comment by logantmg** [comment]
Hi again 😁😁 i talk to the dev of sphinx kernel and he said he will try and also rtl8188eu and rtl8818fu is different because he said rtl8188eu is supported by that kernel so would you please make a driver for rtl 8188fu

**Comment by rithvikvibhu** [comment]
Yes, EU and FU are different. This module supports EU.
Since you have an FU and sphinx doesn't support it yet, there's nothing this module can do right now.

**Comment by logantmg** [comment]
Ok so if developer accept my request and he makes it support then will it work itself or i need driver? And there could be many peoples who have same adapter as mine this could them too so why don't you give a try 😅😅

**Comment by rithvikvibhu** [comment]
Yes it will work.

**Comment by logantmg** [comment]
Then why do we need your firmware?😅😅 Can you explain me because I'm noob

**Comment by rithvikvibhu** [comment]
This module only provides some extra files that are (sometimes) needed by the adapters. You could just manually place these files in /etc/firmware, but that breaks safetynet. This Magisk module only adds them systemlessly, not breaking safetynet.

Apart from this, the kernel must also support the adapter.
