### ISSUE TITLE
[Request] RT5370 support

### ISSUE THREAD

**Issue by Deadpool2000** [rithvikvibhu/nh-magisk-wifi-firmware#43]
Sir please add support for Ralink RT5370 adapter

**Comment by rithvikvibhu** [comment]
See #28.

**Comment by Deadpool2000** [comment]
Drivers
[STA_DPA_BETA_RT5X_JB_V2.6.1.0_20121123.tar.gz](https://github.com/rithvikvibhu/nh-magisk-wifi-firmware/files/4191975/STA_DPA_BETA_RT5X_JB_V2.6.1.0_20121123.tar.gz)

**Comment by Deadpool2000** [comment]
Firmware file

**Comment by rithvikvibhu** [comment]
That looks more like a driver.

This module only provides some extra files that are (sometimes) needed by the adapters. You could just manually place these files in /etc/firmware, but that breaks SafetyNet. This Magisk module only adds them systemlessly, not breaking SafetyNet.

Apart from this, the kernel must also support the adapter.
