### ISSUE TITLE
Add support for MW300uh

### ISSUE THREAD

**Issue by paolosezart** [rithvikvibhu/nh-magisk-wifi-firmware#44]
The Redmi Note 4X phone, the core nethunter, an external adapter with the RT3070 chipset work well. And the external adapter Mercusys MW300UH chipset RTL8192EU does not work. In the terminal, upon request, lsusb issues a device 2c4e:0104. [Here for the main linux](https://github.com/Mange/rtl8192eu-linux-driver/blob/realtek-4.4.x/os_dep/linux/usb_intf.c) (line 215) there is a solution. Can you compile this for the magisk module? It would be very cool, since the network catches the adapter very well, but the phone does not want to work with it, although the description of the module has RTL8192EU.

**Comment by rithvikvibhu** [comment]
Here's the thing. This module only provides some extra files that are (sometimes) needed by the adapters. You could just manually place these files in /etc/firmware, but that breaks SafetyNet. This Magisk module only adds them systemlessly, not breaking SafetyNet.

Apart from this, the kernel must also support the adapter.

This module has the files required for RTL8192. If it doesn't work, then it's mostly related to the kernel.
