### ISSUE TITLE
Please add firmware

### ISSUE THREAD

**Issue by hartotarigan** [rithvikvibhu/nh-magisk-wifi-firmware#46]
Please add firmware rtl8188eus

**Comment by rithvikvibhu** [comment]
Here's the thing. This module only provides some extra files that are (sometimes) needed by the adapters. You could just manually place these files in /etc/firmware, but that breaks SafetyNet. This Magisk module only adds them systemlessly, not breaking SafetyNet.

Apart from this, the kernel must also support the adapter.

This module has the files required for RTL8188. If it doesn't work, then it's mostly related to the kernel.
