### ISSUE TITLE
Atheros AR9271

### ISSUE THREAD

**Issue by marxilla** [rithvikvibhu/nh-magisk-wifi-firmware#47]
Hi I'm not sure if I submitted this correctly. I'm trying to get my Alfa wireless adapter to work again. It doesn't work with the new nethunter updates. Thanks!

**Comment by rithvikvibhu** [comment]
Was it working before the update?
What version did you update from and to which version?

AR9271 isn't listed in the readme under "supported chipsets", but its files are included right from v1 of this module.

**Comment by newszone** [comment]
I have Alfa AthrosAR9271how i use this on oneplus6 nethunter or termux please help.

**Comment by marxilla** [comment]
It was working properly after I removed the Magisk ADB module. I think it changed the way my USB port behaved. Sorry for the delay...you know...COVID

**Comment by rithvikvibhu** [comment]
Sweet, closing since it's working.
