### ISSUE TITLE
RTL8188EUS

### ISSUE THREAD

**Issue by AndraxBoy** [rithvikvibhu/nh-magisk-wifi-firmware#49]
Pls, can you add support RTL 8188 EUS (Id:2357:0111) driver?

**Comment by AndraxBoy** [comment]
https://github.com/aircrack-ng/rtl8188eus

**Comment by kimocoder** [comment]
Yeah, I made newer/netter driver today.

rtl8188eus will be deprecated.
https://github.com/kimocoder/realtek_wifi is under development.

Much easier driver, it depends/runs on existing binaries instead of kernel module.

I may add it in Magisk in a week or so.

**Comment by kimocoder** [comment]
Everything is better with the new driver, mac80211, portable, supports frame injection and so on..

**Comment by AndraxBoy** [comment]
Thx, i will wait...

**Comment by AndraxBoy** [comment]
Will it support injections?
