### ISSUE TITLE
Please add this chipset [RT5370]

### ISSUE THREAD

**Issue by TuserAhammed** [rithvikvibhu/nh-magisk-wifi-firmware#50]
Tenda w311m adapter,,, add in nethunter,,,, this adapter chipset is Ralink rt5370,,,, please add this

**Comment by rithvikvibhu** [comment]
From what I can find online, RT5370 uses `rt2870.bin`. Have you tried using this? Might just work.

**Comment by Shubhamvis98** [comment]
i thing you have to close this issue
RT5370 uses rt2870.bin
**dmesg log**
![dmesg](https://user-images.githubusercontent.com/43336210/97774580-0eead680-1b7f-11eb-9f28-6c9b1739a76c.png)
**airmon-ng**
![rt5370](https://user-images.githubusercontent.com/43336210/97774443-d0085100-1b7d-11eb-9cdb-c6cf012da39c.png)

**Comment by rithvikvibhu** [comment]
Sweet. Thanks for confirming @Shubhamvis98!
