### ISSUE TITLE
RTL-8188EUS ?

### ISSUE THREAD

**Issue by nutrikazuma** [rithvikvibhu/nh-magisk-wifi-firmware#64]
Hi guys, good morning (at last for me)! LoL

This is a question, not an issue, but don't know where to post it so here I am. 😅

I have a TP-Link TL725n I'm trying to use on Nethunter but without success, so I'm here to ask if this module works with this adapter, because it uses this RTL-8188EUS chip and I see that this module have support for RTL-8188 EU and FTV, but said nothing about EUS. 

Ok, I'm from Brazil and my English are a little rusted so sorry for something wrong, ok, thanks. LoL

**Comment by fubefube** [comment]
Help us peeople

**Comment by ttlns** [comment]
Dublicate https://github.com/rithvikvibhu/nh-magisk-wifi-firmware/issues/76
You might close your issue
