### ISSUE TITLE
TL WN727N support

### ISSUE THREAD

**Issue by fyezool** [rithvikvibhu/nh-magisk-wifi-firmware#7]
Hi dev, is it possible to support TL WN727N driver as well? Thanks

**Comment by rithvikvibhu** [comment]
Which version is that? (V1, V2, V3 or V4)

**Comment by fyezool** [comment]
Its v2

**Comment by rithvikvibhu** [comment]
Whoops, my bad. It doesn't look like V2 exists. Just 1, 3 and 4. Can you check again? Or send a pic of the sticker.

**Comment by fyezool** [comment]
https://imgur.com/gallery/lnRKVKv

Turn out mine is v4.1. Im sorry for the confusion

**Comment by rithvikvibhu** [comment]
v4 uses MediaTek MT7601U which is already supported. It's likely something not related to missing drivers. Can you send a `dmesg` log?

**Comment by rithvikvibhu** [comment]
You should see the adapter with `iwconfig`.

If it does, test injection from here: https://www.aircrack-ng.org/doku.php?id=injection_test

727N supports injection, so it should work.

**Comment by fyezool** [comment]
Unfortunately I can't see its listed on iwconfig as well. Thanks for the help though. Gonna close this and give up the nethunter
